### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mungvt** [bizzyvinci/cosmos-etl#1]
Hi friend, I see you are trying to build a ETL on cosmos network and me too. Can I collaborate with you?

**Comment by bizzyvinci** [comment]
This project is greatly inspired by [blockchain-etl](https://github.com/blockchain-etl) and towards an [hackathon](https://evmos2022.devpost.com). The 2 main task is adding messages to the etl and building airflow for gcp. I'm taking a short break right now but you can contact me via email as seen on my profile.
